channels:
  - conda-forge
  - defaults
dependencies:
  - bilby
  - bilby_pipe
  - cython
  - gcc_linux-64
  - gsl
  - gxx_linux-64
  - lapack =3.6.1
  - numpy
  - pip
  - python >=3.9
  - schwimmbad <=0.3.2
  - pip:
    - bilby @ git+https://git.ligo.org/charlie.hoy/bilby.git@ifo_plugin
    - bilby_lisa
    - bilby_pipe @ git+https://git.ligo.org/charlie.hoy/bilby_pipe.git@input_plus_det_plugin
    - parallel_bilby @ git+https://git.ligo.org/charlie.hoy/parallel_bilby.git@input_plus_parser
    - bbhx @ git+https://github.com/mikekatz04/BBHx.git@4fff509b5afc770f40e492f946b0b2ac2aedbf5b
