name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: "3.10"
          conda-channels: anaconda, conda-forge

      - name: Install dependencies
        run: |
          conda install python=3.10 numpy schwimmbad gcc_linux-64 gxx_linux-64 gsl lapack=3.6.1 Cython
          python -m pip install .
          python -m pip install --force-reinstall "git+https://git.ligo.org/charlie.hoy/bilby.git@ifo_plugin" "git+https://git.ligo.org/charlie.hoy/bilby_pipe.git@input_plus_det_plugin" "git+https://git.ligo.org/charlie.hoy/parallel_bilby.git@input_plus_parser" "git+https://github.com/mikekatz04/BBHx.git"

      - name: Build documentation
        run: |
          cd docs
          make clean
          make html
          touch _build/html/.nojekyll
          cd ../
          mv docs/_build/html docs
